{% set name = "datacube" %}
{% set version = "1.9.13" %}
{% set sha256 = "699b44784a5695209cdba4f90b98f08de11cce6e3ae3877df19555c54e2420c7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - datacube = datacube.scripts.cli_app:cli
    - datacube-search = datacube.scripts.search_tool:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm >=3.4
    - toml
  run:
    - python >={{ python_min }}
    - affine
    - antimeridian <0.4.5
    - attrs >=18.1
    - boto3
    - botocore
    - cachetools
    - click >=8.0
    - cloudpickle >=0.4
    - dask-core
    - deprecat
    - distributed
    - pyproj >=2.5
    - shapely >=2
    - jsonschema >=4.18
    - lark
    - netcdf4
    - numpy >=1.26.0
    - odc-geo >=0.5.0
    - odc-loader <=0.6.3
    - odc-stac >=0.5.0
    - pandas
    - packaging
    - psycopg2
    - python-dateutil
    - pyyaml
    - rasterio >=1.3.11
    - sqlalchemy >=2.0
    - alembic
    - geoalchemy2 >=0.17.0
    - xarray >2022.6.0
    - ruamel.yaml
    - toolz

test:
  imports:
    - datacube
    - datacube.api
    - datacube.drivers
    - datacube.drivers.netcdf
    - datacube.drivers.postgres
    - datacube.drivers.postgis
    - datacube.cfg
    - datacube.index
    - datacube.model
    - datacube.scripts
    - datacube.storage
    - datacube.testutils
    - datacube.ui
    - datacube.utils
    - datacube.utils.aws
  commands:
    - pip check
    - datacube --help
    - datacube-search --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.opendatacube.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Data analysis environment for earth observation data
  description: |
    Open Data Cube Core provides an integrated gridded data analysis environment
    for decades of analysis ready earth observation satellite and related data
    from multiple satellite and other acquisition systems.
  doc_url: http://datacube.readthedocs.io
  dev_url: https://github.com/opendatacube/datacube-core

extra:
  recipe-maintainers:
    - pjonsson
    - Ariana-B
    - andrewdhicks
    - SpacemanPaul
    - jeremyh
    - Kirill888
    - omad
    - snowman2
